name: ci-dev

on: [workflow_dispatch]

jobs:
  dev:
    name: dev ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: ["ubuntu-22.04", "macos-13", "windows-2019"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v4
      # run vcvars on windows
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Procgen Build
        run: python -m pip install -e procgen-build

      - name: Test
        run: python -u -m procgen_build.dev_test
