name: ci

on: [workflow_dispatch]

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: ["ubuntu-22.04", "macos-10.15", "windows-2019"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v4
      # run vcvars on windows
      - uses: ilammy/msvc-dev-cmd@v1

      # warning: if something is changed so that the cached dependencies are not correct
      # this cache will not notice and the build will be slow, to fix this, increment the
      # version in the key
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-dependencies-v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Procgen Build
        run: python -m pip install -e procgen-build

      - name: Build
        run: python -u -m procgen_build.build_package

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  dev:
    name: dev ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: ["ubuntu-18.04", "macos-10.15", "windows-2019"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v4
      # run vcvars on windows
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Procgen Build
        run: python -m pip install -e procgen-build

      - name: Test
        run: python -u -m procgen_build.dev_test
